version: "3.7"
services:
  pomodoro:
    container_name: pomodoro
    build:
      context: ./pomodoro

  todos:
    container_name: todos
    build:
      context: ./todos

  orchestrator:
    container_name: orchestrator
    ports:
      - 80:80
    depends_on:
      - pomodoro
      - todos
    build:
      context: .
